language: php
php:
  - '7.1'
  - '7.2'
  - hhvm
  - nightly

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit --bootstrap vendor/autoload.php

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

notifications:
  on_success: never
  on_failure: always